// <auto-generated />
using System;
using BBRRevival.Server.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBRRevival.Server.Migrations
{
    [DbContext(typeof(SqliteDBContext))]
    [Migration("20250722185655_IImprovePlayer")]
    partial class IImprovePlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BBRRevival.Common.Model.ClientConfigModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientConfigs");
                });

            modelBuilder.Entity("BBRRevival.Common.Model.PlayerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientConfigID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diamonds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacebookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCheater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemDbVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCarBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMcBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NinjaCreationTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YoutubeSubscriberCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientConfigID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BBRRevival.Common.Model.PlayerModel", b =>
                {
                    b.HasOne("BBRRevival.Common.Model.ClientConfigModel", "ClientConfig")
                        .WithMany()
                        .HasForeignKey("ClientConfigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
