// <auto-generated />
using System;
using BBRRevival.Server.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBRRevival.Server.Migrations
{
    [DbContext(typeof(SqliteDBContext))]
    [Migration("20250725142605_MakeClientConfig")]
    partial class MakeClientConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BBRRevival.Common.Model.ClientConfigModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BoltsAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarRefreshMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinsAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRank1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRank2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRank3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRank4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRank5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRank6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyGemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiamondsAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FbConnectReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreshFreeCoolDown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreshFreeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreshFreeInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InRaceDiamondSpawnProbability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeysAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumTournamentNitros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OfferCooldownMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OfferDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuperLikeRefreshMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriesForAd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriesForGems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriesGemPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoAdCoolDown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoAdCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ClientConfigs");
                });

            modelBuilder.Entity("BBRRevival.Common.Model.PlayerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AcceptNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdventureLevelsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BigBangPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Boosters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BundlesPurchased")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CarBoosterRefreshTimeLeft")
                        .HasColumnType("REAL");

                    b.Property<int>("CarBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CarHandicap")
                        .HasColumnType("REAL");

                    b.Property<int>("CarTrophies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardPurchases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ClaimedTutorials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientConfigID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CoinDoubler")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompletedSurvey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatorLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorRankingDelta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diamonds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DirtBikeBundle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EditorResources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FbClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForumClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GachaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCenterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasJoinedTeam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HatsPurchased")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCheater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemDbVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSeasonEndCarTrophies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSeasonEndMcTrophies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCarBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMcBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<double>("McBoosterRefreshTimeLeft")
                        .HasColumnType("REAL");

                    b.Property<int>("McBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<float>("McHandicap")
                        .HasColumnType("REAL");

                    b.Property<int>("McRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McTrophies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NameChangesDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewLevelsRated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NinjaCreationTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingSpecialOfferChests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedMinigameCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RacesThisSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RacesWon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SuperLikeRefreshTimeLeft")
                        .HasColumnType("REAL");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamKickReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamRoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSuperLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentBoosters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrailsPurchased")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Upgrades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VarRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YoutubeSubscriberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("teamRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientConfigID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BBRRevival.Common.Model.PlayerModel", b =>
                {
                    b.HasOne("BBRRevival.Common.Model.ClientConfigModel", "ClientConfig")
                        .WithMany()
                        .HasForeignKey("ClientConfigID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
