using System;

// Token: 0x02000468 RID: 1128
public class LanguageEn : Translation
{
	// Token: 0x06001EEA RID: 7914 RVA: 0x00164596 File Offset: 0x00162996
	public string GetString(int _index)
	{
		if (this.strings.Length > _index)
		{
			return this.strings[_index];
		}
		return string.Empty;
	}

	// Token: 0x04002687 RID: 9863
	public string[] strings = new string[]
	{
		"Suomi",
		"Français",
		"Italiano",
		"Deutsch",
		"Español",
		"Português",
		"Português (Br)",
		"English",
		"Español (LatAm)",
		"Russian",
		"Go!",
		"Ok",
		"Play",
		"Upgrade",
		"Upgrades",
		"Hats",
		"News",
		"Settings",
		"Paused",
		"Resume",
		"Exit",
		"Create",
		"Race",
		"Race!",
		"End race",
		"Next Race!",
		"Race again",
		"Checking for updates...",
		"Loading...",
		"Building level...",
		"Connecting...",
		"Upgrade\nvehicle",
		"Play again!",
		"Continue",
		"You finished",
		"Performance",
		"Get from chest",
		"Unlocks at %1",
		"How did you like my level?",
		"MegaLike",
		"You megaliked this level",
		"You double-liked this level",
		"You liked this level",
		"You disliked this level",
		"You double-disliked this level",
		"Available again in",
		"Try Again!",
		"Skip Level",
		"Get it!",
		"Yes",
		"No thanks",
		"Cancel",
		"tries left",
		"Slots full",
		"Heat",
		"Install",
		"Level up",
		"Level up!",
		"Good or bad?",
		"Delete",
		"Get more",
		"Back",
		"Spin",
		"Friends",
		"Connect to Facebook to automatically find your friends.",
		"Mutual follow",
		"Following",
		"You're not following anyone who isn't also following you.",
		"Follow",
		"Unfollow",
		"Latest levels by Friends & Followees",
		"No levels found!",
		"User has no levels",
		"Not in team",
		"Stats",
		"Total Trophies",
		"Big Bang Points",
		"Levels made",
		"Followers",
		"Likes earned",
		"Mega Likes earned",
		"Adventure levels completed",
		"Races won",
		"Races started",
		"Items found",
		"Good or Bad levels rated",
		"Big Bang Points are earned by having over 3000 Trophies on any vehicle when season ends.",
		"Search Players and Levels",
		"Players found",
		"No players found",
		"Levels found",
		"Level",
		"Open",
		"Open now",
		"Coins",
		"Gems",
		"Hat",
		"Nitros",
		"For all vehicles",
		"Common part",
		"Rare part",
		"Epic part",
		"Common item",
		"Rare item",
		"Epic item",
		"Common hat",
		"Rare hat",
		"Epic hat",
		"Resources",
		"Contains at least:",
		"Gold coins",
		"Parts",
		"Items",
		"VEHICLE UPGRADES",
		"EDITOR ITEMS",
		"RARE",
		"EPIC",
		"WOODEN",
		"BRONZE",
		"SILVER",
		"GOLDEN",
		"BIG BANG",
		"RARE CHEST",
		"EPIC CHEST",
		"WOODEN CHEST",
		"BRONZE CHEST",
		"SILVER CHEST",
		"GOLDEN CHEST",
		"BIG BANG CHEST",
		"Surprise Chest",
		"Free Chest",
		"Coin roulette",
		"Adventure chest",
		"Racing chest",
		"Music",
		"Sounds",
		"Left-Handed drawing",
		"Support",
		"Forum",
		"Low-end mode (30fps)",
		"Change your name",
		"Client version",
		"Disconnect from Facebook",
		"Connect to Facebook",
		"Settings",
		"Racing unlocks\nafter level 6",
		"Upgrade your Offroader to %1 to unlock. ",
		"Unlock DIRTBIKE at %1",
		"Dirtbike Locked",
		"Get 3 Map Pieces!",
		"Get 3 gems",
		"You have %1 out of %2 %3",
		"Map pieces",
		"Gems",
		"SPIN",
		"MOVE",
		"Optimize performance?",
		"The game seems to be running a bit slow. Optimize graphics for a smoother experience?\n\nYou can change this from <color=#aaff77>settings</color> at any time.",
		"Please update",
		"Chest Reminder",
		"Chest Reminder",
		"You cannot receive MAP PIECES before <color=#AFFF6E>Adventure Chest</color> has been opened!\n\nPlay level anyways?",
		"Trophy warning",
		"You have <color=#ffa911>1 more try</color> to improve your Trophy earnings!\n\nEnd race already?",
		"You have<color=#ffa911> %1 tries</color> to improve your Trophy earnings!\n\nEnd race already?",
		"Hi there!",
		"Do you like our game?",
		"Yes",
		"No",
		"Great!",
		"Would you like to rate this game?",
		"Rate now!",
		"Later",
		"Sorry to hear that",
		"We would love to hear what's wrong. Please let us know!",
		"Contact us",
		"Not now",
		"What is your name?",
		"Changing your name...",
		"Disconnecting from facebook...",
		"Next free CHEST at %1cc",
		"New parts appear in",
		"Purchase",
		"Maxed out",
		"Waiting for store",
		"Upgrades",
		"Chests",
		"Gems",
		"Coins",
		"Coins",
		"Purchased chests\nopen immediately!",
		"Gems",
		"You bought %1 gems!",
		"Not enough %1! Earn more by playing!",
		"Not enough coins",
		"Get the missing %1 COINS by using %2 GEM?",
		"Get the missing %1 COINS by using %2 GEMS?",
		"Get coins",
		"Not enough gems",
		"Enter shop to get more?",
		"Enter shop",
		"Shop",
		"Maximum level complexity reached! Remove some items to add more.",
		"Out of stock.\nDo you want to buy one?",
		"Maximum %1 amount is %2.",
		"My\nLevels",
		"Search",
		"Friend\nLevels",
		"All friends",
		"Latest levels",
		"Create new level",
		"Build",
		"Drive",
		"Save &\nExit",
		"Saved level",
		"Editor Items",
		"Total likes",
		"Total earnings",
		"Total followers",
		"Your Live Levels",
		"GO LIVE with your unfinished levels to make room for new drafts!",
		"Player vehicle",
		"Choose vehicle",
		"Vehicle",
		"Offroader",
		"Dirtbike",
		"Slow and easy",
		"Fast and challenging",
		"Game mode",
		"Choose game mode",
		"Adventure",
		"Racing",
		"Three map pieces to collect",
		"Time attack competition",
		"Dome size",
		"Choose dome size",
		"Tiny Dome",
		"Big Dome",
		"Huuuge Dome",
		"Compactly sized area",
		"Unleash your imagination, here's room for it!",
		"Massive bubble that can cover an entire town",
		"Cardboard Box",
		"Metal Box",
		"Rock",
		"Wooden Plank",
		"Metal Plank",
		"Concrete",
		"Concrete Ramp",
		"Concrete Slope",
		"Crumbling Platform",
		"Rolling Boulder",
		"Treadmill",
		"Automatic Elevator",
		"Manual Elevator",
		"Big Gear",
		"Small Gear",
		"Fan",
		"Bouncer",
		"Force Field",
		"Portal",
		"Spikes",
		"Exploding Barrel",
		"Crusher",
		"Air Bomb",
		"Sign",
		"Tree",
		"Artistic Stone",
		"Picket Fence",
		"Metal Fence",
		"Confetti",
		"Pyrotechnics",
		"Chicken Surprise",
		"Pieces",
		"Gadgets",
		"Dangers",
		"Decorations",
		"Enkku",
		"Admin password",
		"Leaderboards",
		"Offroader Leaderboards",
		"Dirtbike Leaderboards",
		"Global",
		"Local",
		"Friends",
		"Beginner league",
		"Amateur league",
		"Novice league",
		"Pro league",
		"Master league",
		"Extreme league",
		"Elite league",
		"Big Bang league",
		"*Beginner*%1league",
		"*Amateur*%1league",
		"*Novice*%1league",
		"*Pro*%1league",
		"*Master*%1league",
		"*Extreme*%1league",
		"*Elite*%1league",
		"*Big Bang*%1league",
		"Unlocks upgrades:",
		"league",
		"All chests",
		"LEVEL UP",
		"Spark plugs",
		"Makes a bike faster.",
		"Caffeine fuel",
		"High octane, high caffeine.",
		"Electronics",
		"Known to be a bit flimsy.",
		"Insurance",
		"Increased confidence.",
		"Transmission",
		"Solid metal gears.",
		"Organic oil",
		"Produced locally.",
		"Suction cups",
		"Increases traction.",
		"Brake discs",
		"Serious stopping power.",
		"Filler",
		"Stardust is the best stuff for tires.",
		"Natural rubber",
		"Eco-products are gaining traction.",
		"Bubblegum",
		"Super sticky.",
		"Wonderglue",
		"Extreme grip.",
		"Handles",
		"Improves driveability.",
		"Gyroscope",
		"Superior flips and spins.",
		"Shocks",
		"Smooth ride over rough terrain.",
		"Microchip",
		"PCMR v5.0",
		"Seat warmer",
		"Everybody loves a warm seat.",
		"Front fork",
		"Harder, better, faster stronger.",
		"Turbocharger",
		"Makes a car faster.",
		"Gear oil spray",
		"Fast like a greased lightning.",
		"Battery",
		"Don't get shocked.",
		"Tank cap",
		"Fuel leaks can be dangerous.",
		"Filter system",
		"Cleans everything.",
		"Gear stick",
		"Swift gear changes.",
		"Studs",
		"Increases traction.",
		"Brake fluid",
		"Essential for brakes.",
		"Bucket of sand",
		"Low tech solutions for low grip situations.",
		"Traction sensor",
		"Sometimes a computer knows best.",
		"Wheel bolts",
		"Don't lose your wheels.",
		"Cosmic tires",
		"Won't slip even on moon dust.",
		"Steering wheel",
		"Improves driveability.",
		"Pedals",
		"It would be a shame if your foot slipped.",
		"Air conditioning",
		"Don't overheat.",
		"Cup holder",
		"Your morning brew is now secure.",
		"Seat",
		"Now with adjustment lever.",
		"Wondertree",
		"The scent is called What On Earth.",
		"Flip boost power",
		"Charge stronger boosts by performing FLIPS.",
		"Nitro power",
		"NITRO button charges a stronger boost.",
		"Nitro amount",
		"Increases the amount of available NITROS.",
		"Coin magnet",
		"Increases the radius of automatic COIN pull.",
		"Nitro boost length",
		"Extends the duration of NITRO boost.",
		"Flip boost length",
		"Extends the duration of FLIP boost.",
		"Speed",
		"Grip",
		"Handling",
		"Upgrade Parts",
		"Racing Helmet",
		"Red Cap",
		"Mushroom Afro",
		"Barbaric Helmet",
		"Cowboy Hat",
		"Horse Head",
		"Chicken",
		"Knight's Helmet",
		"Carnival Mask",
		"Hat of the Ugly",
		"Pilot Goggles",
		"Deal With These",
		"Golden Shades",
		"Goldfish",
		"VR Goggles",
		"Motocross Helmet",
		"Hats",
		"This planet is full of hidden treasures! Ready to explore?",
		"Born ready!",
		"The map is complete, you got a treasure chest!",
		"Sweeeet",
		"Pop it open and get yourself some good stuff.",
		"Mmmm, loot!",
		"What should we call you?",
		"My name is...",
		"You can SUPERCHARGE coin rewards by spinning the roulette. Try it out!",
		"Ka-ching!",
		"Trophy Racing is now unlocked!",
		"Oh, racing?",
		"Race against other players and earn extra treasures!",
		"Sounds promising!",
		"When someone publishes a level, it appears on the sky.",
		"Oh?",
		"Playing these NEW levels is a good way to earn gems!",
		"Cool!",
		"You can now explore another planet!",
		"Really?",
		"Swap to DIRTBIKE for new adventure and racing challenges!",
		"Will do!",
		"That DIRTBIKE looks so agile and furious!",
		"Mhm",
		"Try not to hurt yourself!",
		"Fingers crossed",
		"Your job here is to outrun the opponents.",
		"Nice!",
		"Flips, nitros, and upgrades can greatly help you!",
		"Good to know",
		"Winning enough TROPHIES gets you to leaderboards and higher leagues.",
		"Mmmm, trophies",
		"Higher leagues unlock new upgrades and level-ups treasure chests.",
		"Smooooth",
		"Max complexity reached",
		"Teams",
		"Team Up",
		"Team Suggestions",
		"Teams earn <color=#f051d9>FREE GEMS</color> every week from Racing Seasons!",
		"CREATE\nNew Team",
		"Team needs at least %1 players to start earning <color=#EA35FB>season rewards</color>.",
		"Team name has to have at least 3 characters!",
		"You need %1 coins to create a team!",
		"Racing season",
		"Season ends in %1",
		"Top team!",
		"Team trophies",
		"Team Members",
		"Create new team",
		"Create",
		"Team name",
		"Description",
		"Required Trophies",
		"Join Type",
		"Team creator is automatically the TEAM LEADER",
		"World Rank",
		"Members",
		"Chat",
		"My Team",
		"Top Teams",
		"Top Players",
		"Instantly earn <color=#ffffff>%1</color>",
		"Closed",
		"Open",
		"Friends Only",
		"%1 Required",
		"Team Full",
		"Join Team",
		"Joining team...",
		"Creating team...",
		"New season!",
		"Your team earned a <color=#f051d9>season reward</color>! Here is your share, good job!",
		"You didn’t earn <color=#f051d9>season rewards</color>, as you’re not a member of any team. Join a team for the new season!",
		"Your team didn't have enough members to be eligible for <color=#f051d9>season rewards</color>. Find more members for new season!",
		"You didn't have enough Trophies to claim a share of <color=#f051d9>season reward</color>. Earn more Trophies on this season!",
		"Claim",
		"Notifications",
		"Lower performance devices work better with 30 fps mode. Try this option if your game feels slow.",
		"Love us!",
		"You have a chest ready to open!",
		"You are now being followed by %name%!",
		"You have %amount% new followers!",
		"People you follow have created %amount% new levels!",
		"Racing season ends in one day, get more Trophies to maximize season reward!",
		"Racing season ends in one day, get more Trophies to maximize Big Bang Points!",
		"New racing season has begun! Come claim your season reward!",
		"New racing season has begun! Make your team proud!",
		"New racing season has begun! Team up and start earning season rewards!",
		"You have earned some coins from levels you created. Come claim them!",
		"You have earned %amount% coins from levels you created. Come claim them!",
		"Your levels got %superLikesAmount% new megalikes and %likesAmount% new likes! You have earned %amount% coins. Come claim them!",
		"Your levels got %likesAmount% new likes! You have earned %amount% coins. Come claim them!",
		"Your levels got %superLikesAmount% new megalikes! You have earned %amount% coins. Come claim them!",
		"You have earned %amount% coins. Come claim them!",
		"You were kicked from team: %kickReason%",
		"Your team promoted you as %memberStatus%!",
		"New upgrade parts arrived to Shop!",
		"You have %chestAmount% chests ready to open!",
		"Earn coins from Likes and Mega-Likes",
		"You haven't published any levels!",
		"Language",
		"Enter new name",
		"You earned <color=#FED742> %1 </color> Big Bang Points!",
		"Okay, do it!",
		"Gold mixer",
		"Nice! Some of the Copper coins turned into GOLD on this run.",
		"Gem rain",
		"HUUUUUGE WIN! All coins turned into GEMS on this run!",
		"Golden streak",
		"Alchemy! All Copper has turned GOLD on this run!",
		"Gold mania",
		"OMG! On this run you get GOLD and SUPERGOLD instead of Copper coins.",
		"Gold rush",
		"MEGA WIN! Everything is SUPERGOLD on this run!",
		"Royal streak",
		"JACKPOT! All coins are SUPERGOLD with some shiny GEMS in the mix!",
		"Get super rewards",
		"Supercharge your coins,\nget GOLD or GEMS for the next run!",
		"Coming soon!",
		"Write a team name",
		"No teams to show",
		"Current season",
		"Top 10 teams win an increased <color=#FED742>season reward</color>, shared among top 10 players of the team.",
		"Vehicle Trophies that exceed 3000 will be converted to <color=#FED742>Big Bang Points</color> at the end of the season.",
		"Leave",
		"Team settings",
		"Only the Team Leader can change these settings",
		"Save",
		"Saving team...",
		"Special",
		"Race yourself to %1 (%2 <color=#FED742>Trophies</color>) on any vehicle to unlock Teams.",
		"Teams locked",
		"Fill up!",
		"Fill up nitros",
		"Watch ad",
		"2 nitros",
		"Fill to max!",
		"Team up",
		"and join the racing season!",
		"<color=#FC3FF8>Season rewards</color> given every week",
		"Browse teams",
		"Dirtbike Bundle",
		"Coin Booster",
		"Permanently increase Copper Coin value to 5x.",
		"Your Copper Coins are now 5x more valuable",
		"Exclusive hat",
		"Special Offer",
		"No friends found.",
		"Tell them to get the game and come play with you.",
		"Items are found from chests!",
		"by",
		"Like-a-Meter 3000™",
		"Edit",
		"Go live!",
		"Keep\nediting",
		"Go live if your level is fun to play!",
		"Publish Level",
		"Level Screenshot",
		"Level Description",
		"Level Name",
		"Your time",
		"Bag of Gems",
		"Barrel of Gems",
		"Box of Gems",
		"Crate of Gems",
		"Pack of Gems",
		"Stacks of Gems",
		"Trunk of Gems",
		"Vault of Gems",
		"Bundle",
		"Tap for more info!",
		"Or get it now!",
		"Most\npopular!",
		"Best\nvalue!",
		"Purchased",
		"Jar of Gold",
		"Barrel of Gold",
		"Vault of Gold",
		"Sorry!\nThe area can not be changed to a smaller size",
		"HOLD the button, and simultaneously\nuse another finger to DRAW ground",
		"HOLD the button, and simultaneously\nuse another finger to ERASE ground",
		"Ejected!",
		"Exploded!",
		"Electrified!",
		"Neck snap!",
		"Creating GIF",
		"Sending to server",
		"Tap to SHARE GIF",
		"Recording...",
		"Gif sending failed",
		"Tap to try again",
		"Are you sure you want to leave %1?",
		"Leave team?",
		"AndroiMers’ Mr. Bacon Wig",
		"Reversal’s Fancy Crown",
		"McSportzHawk’s Hawk Mask",
		"Bootramp’s Robot Mask",
		"Petard’s BBR-01 Helmet",
		"Spencer23$’s Swag Hat",
		"TheAlvaro845’s Kitty Cat",
		"FLIPS will boost you!",
		"Protect your HEAD",
		"<color=#ff5050>Red stuff</color> is dangerous!",
		"<color=#66ff99>Lean forward</color> on steep hills!",
		"Control your FRONT WHEEL to succeed here.",
		"<color=#AFFF6E>Racing Chest</color> hasn't been opened yet.\n\nYou can still win <color=#FED742>Trophies</color>.",
		"Are you sure you want to <color=#ff3a17>DELETE</color> %1?\n\nAll items will be returned to inventory!",
		"Unable to connect with the server. Check your internet connection and try again.",
		"Servers are down for maintenance.",
		"There was an error connecting with the server.",
		"Connection error",
		"Team not found!",
		"Team was not found. It may have been deleted.",
		"Session expired",
		"Your account was used on another device, press retry to login again.",
		"Try left",
		"Hat found!",
		"Hidden hat",
		"Following %1 unlocked a hidden hat!",
		"Next\nSurprise",
		"Select Language",
		"Publishing...",
		"Sending to server, please wait",
		"Saving...",
		"Connect to Facebook to save your game to cloud and play on multiple devices.",
		"Saved game found",
		"Another saved game was found from cloud!\nChoose which one to keep:",
		"Current:",
		"Cloud:",
		"Confirm selection",
		"Your game will be saved to cloud. This will overwrite the older saved game in cloud.",
		"Saved game from cloud will be loaded. This will overwrite the currently saved game on device.",
		"Confirm",
		"Levels completed:",
		"Change name?",
		"You can change your name only ONCE!",
		"Kick player",
		"Demote player",
		"Promote player",
		"Connect",
		"Done!",
		"Purchase completed.",
		"You bought",
		"Go to shared level?",
		"Exit current level and go to the level that was shared?",
		"Retry",
		"Level not found",
		"You were kicked from team: %kickReason%",
		"Out of stock",
		"Connecting to facebook...",
		"Cannot save game to iCloud, please check your system settings.",
		"Game will be saved to iCloud",
		"Shards",
		"Shard",
		"Get 3 Shards",
		"Tap to sign in",
		"Tap to sign out",
		"Not signed in",
		"Signed in",
		"Achievements",
		"Google Play Games",
		"In order to backup your saved game, Big Bang Racing needs permission to write to device storage. Without backup, your saved data will be lost if you uninstall the game.",
		"Backup your game?",
		"Common Editor Item",
		"Rare Editor Item",
		"Epic Editor Item",
		"Races played",
		"Trophy change",
		"Double up?",
		"collected",
		"Kicking from team...",
		"%1 created a new %2",
		"Adventure level",
		"Racing level",
		"%1 mega-liked %2",
		"%1 was kicked from team by %2. Reason: %kickReason%",
		"%1 joined the team",
		"%1 left the team",
		"New racing season has begun! Last season we got %1 Team Trophies and earned %2 gems!",
		"New planet awaits!",
		"Can't wait until Offroader adventure continues?",
		"Starter pack",
		"Open one Racing and Adventure chest instantly!",
		"Begin Dirtbike adventure NOW!",
		"New Planet",
		"New Vehicle",
		"Team kick feature is now live! Go check if your team leader kept you in.\n\nIn any case, here is a hat for you!",
		"Boot hat",
		"Hey Team! You need to have at least 5 members in your team to earn rewards!",
		"Tap to Move",
		"By publishing a level, you agree to our Terms of Service.",
		"Report",
		"Is this level offending?\n\nRemember: if the level is too challenging, it's not a reason to report!",
		"Report abuse",
		"Reason:",
		"Kicked from team",
		"Input has to have at least %1 characters.",
		"Orange",
		"Link to %1",
		"%1 Username",
		"Current channel",
		"Channels not found",
		"Channels found",
		"Share your Big Bang Racing experience!",
		"Link your %1 and show your coolest level creation videos and most epic race wins to the Big Bang community!",
		"Link to channel will be displayed in your profile.",
		"YouTube channel",
		"Trails",
		"Bubbles",
		"Feather fever",
		"Fireblast",
		"Mad Cash",
		"Rainbow road",
		"Sci-Fi",
		"Horror",
		"Trails",
		"Check out our YouTube channel to see how this level was created.",
		"As an example, check OUR YouTube channel to see how this level was created!",
		"Show me!",
		"Congratulations!",
		"Your level is now available for others to play.",
		"Did you know? You earn coins when others Like or Megalike your level!",
		"Share this level with your friends!",
		"Share now",
		"Share",
		"Check out my new level!",
		"I created a level called %1 in Big Bang Racing, check it out!",
		"Cool!",
		"Later",
		"YouTube channel ID",
		"You have 10000 unclaimed coins! Come claim them to make room for more!",
		"Team Reward",
		"Gravity Switch",
		"Black Hole",
		"Lost in time and space",
		"Skull Rider",
		"Ha! Puny alien, you think you can beat me, the magnificent SKULL RIDER!",
		"I'm the greatest driver this planet has ever seen!",
		"Why would anyone insist on challenging ME?",
		"You don't stand a chance because you were born a LOSER!",
		"I laugh at your lame attempts! Why do you even try?",
		"I'm fast, what can I say?",
		"What a lame ride, who built that thing?",
		"There is no way you will ever beat ME!",
		"SKULL RIDER is here to stay! You should just STAY AWAY!",
		"Stay slow, you harmless alien challenger. Stay slow.",
		"Too slow! Learn how to cheat and maybe you have a chance!",
		"Wow, that vehicle of yours truly is a piece of garbage!",
		"I heard there's a place for that kind of driving! It's called PLANET SNAIL!",
		"Even if you were twice as fast, you'd still be SLOW!",
		"Roses are red violets are blue, I'm the fastest, what happened to you?",
		"A handy tip, upgrage your vehicle or buy some Power Fuel!",
		"You're not fast enough! You seriously need an upgrade!",
		"You can't beat me like that, open more chests and upgrade your vehicle!",
		"You missed one! That means you are slow AND reckless! Ha!",
		"Hahaha, you missed a spot! When will you learn?!",
		"You're supposed to drive through ALL the checkpoints! Better luck next time, loser!",
		"Why not try and give me a challenge next time?",
		"Drive through all the checkpoints, how can it be so hard?",
		"Aww, the tiny alien is now in even more tiny bits! Learn how to drive, you LOSER!",
		"BOOM! No way you'll ever win racing like that!",
		"That's so lame, even one mistake is too many against ME!",
		"Got stuck? What are you, twelve?",
		"You got squashed!",
		"Why do you keep on trying, it's impossible to beat ME!",
		"Aaaah what a loser! Try and finish next time!",
		"Zzapp! Need a jump start? Hahaha!",
		"Smoking! Black really suits you well!",
		"Ouch, better watch how and where you land! Hahaha!",
		"Uff, believe me, that hurt me more than you!",
		"Are you okay? You don't look so good, hahaha!",
		"What? No! You cheater, how is this possible?",
		"I lost?! This can't be happening, aargh!",
		"Lose? I never lose! Wait, what? NOOOO!",
		"You'll pay for this, I swear! Nobody beats the SKULL RIDER!",
		"Why is this happening to me? Oh, the shame!",
		"What are you, some kind of a super alien?!",
		"I had something in my eye! This is not fair, you hear me!",
		"I will return, faster and stronger! This is not the last you heard of me!",
		"Alright, I get it, I shut up. But not for long!",
		"I hate losing as much as I hate you! I can't believe you beat me!",
		"Boss Battles",
		"Race against the tough Skull Rider!",
		"Oh?",
		"Drive to all of the checkpoints and finish first to win.",
		"Cool!",
		"Win the race against Skull Rider to get a Skull Chest! Skull Chests are rare treats and can only be acquired from the Boss Battles.",
		"Driving through the checkpoints is vital when racing the Skull Rider. Driving through the checkpoints gives you extra boost, but beware, the Skull Rider will get boosts as well! Use the Freeze ability and the Boost ability in smart combinations to beat the Boss Battle.",
		"If you're having a tough time beating Boss Battles, upgrade your vehicle, or buy some Power Fuel to get temporary CC boost!",
		"A new update is available! Get ready to face the Skull Rider in the Boss Battles! Record your own editor videos and post them online!",
		"GET POWER FUEL",
		"Temporarily increase the performance of your vehicle against this Skull Rider.",
		"Super Fuel",
		"Mega Fuel",
		"Jet Fuel",
		"Exit?",
		"You haven't saved your recording. Are you sure you want to exit?",
		"Preview",
		"Discard",
		"News",
		"News",
		"Oops, where'd you go? Found a black hole? Hahaha!",
		"I'm glad for all this multiverse business, happy to see you in another dimension!",
		"Hahaha! That's so funny! Sucked into a black hole, in the middle of race!",
		"Skull Rider Sabotaged!",
		"The next Boss Battle is a bit easier!",
		"Collect all 3 SKULL ORBS and finish first!",
		"You won!",
		"You lost!",
		"Bat Trail",
		"Magic Cauldron",
		"Pumpkin Lantern",
		"Werewolf Mask",
		"Magic Hat",
		"Pumpkin Hat",
		"Blondie",
		"Claim the FREE Bat Trail for a limited time!",
		"Claim your FREE Bat Trail for a limited time! Discover AWESOME new Halloween hats and decorations from chests!",
		"HAPPY HALLOWEEN!",
		"Free",
		"Watch video of this level!",
		"Time left:",
		"Ended",
		"Live Events",
		"Old Announcements",
		"Best Adventure Level",
		"Best Racing Level",
		"Honorable Mentions",
		"Find out more!",
		"TraplightGames Channel",
		"Watch submissions",
		"SUBMIT\nyour entry!",
		"Watch the announcement!",
		"Join the Creation Challenge",
		"Creation Challenge is over",
		"Creation Challenge winners",
		"Join quickly!",
		"Results in…",
		"Check if you won!",
		"Time left to participate:",
		"Results announced in:",
		"Winners get an iPad Pro!",
		"Chance to win an iPad Pro!",
		"Chance to win a pro tablet!",
		"Winners get a tablet!",
		"Active Events",
		"Archives",
		"Hard Hat",
		"Toadie",
		"December update is here! The aliens have discovered a snowy planet full of jingle. Come back every day to claim a unique gift floating in the sky!",
		"Winter Lights",
		"Create festive new levels with these colorful lights!",
		"Gift box",
		"You might have seen these around already, so here’s a big pile of gift boxes for you to create new levels with!",
		"Little Helper Hat",
		"Spread the holiday spirit with one of the most recognizable hats on the planet!",
		"Reindeer Hat",
		"Dress up as the world famous Rangifer tarandus!",
		"Winter Cap",
		"Unlike normal cap, this one can keep you a little warmer!",
		"Pink Cowboy Hat",
		"You can never go wrong with pink!",
		"Unicorn Mask",
		"An upgraded version of the horse mask!",
		"Snow Trail",
		"Use this trail to make your opponents eat your dust— oops, I mean eat your SNOW!",
		"Skull Chest",
		"Skull Rider sends you holiday wishes from the planet of retired antagonists. What a nice gesture!",
		"Sack of Gems",
		"A worthy chunk of gems, delivered to you straight from the shop!",
		"Upgrade Parts",
		"The guys at the shop sent you a day’s worth of upgrade parts!",
		"Rare Upgrade Parts",
		"The guys at the shop sent you a two day’s worth of RARE upgrade parts!",
		"Epic Upgrade Parts",
		"The guys at the shop mailed you three day’s worth of EPIC upgrade parts!",
		"Golden Day",
		"All collectable coins are GOLD today! This ends when next gift arrives.",
		"Discount Day",
		"Upgrade parts in the shop are whopping 90% cheaper today, get them all!",
		"Upgrade Day",
		"Installing upgrades requires 50% less coins today! This ends when next gift arrives.",
		"Nitro Day",
		"Today you have UNLIMITED NITROS! Lasts until next gift arrives, so better start racing!",
		"Holiday Gift Calendar",
		"Claim Gift!",
		"Day: %1",
		"Opens in %1",
		"Open now!",
		"A surprise gift within a surprise gift? We need to go deeper!",
		"An esteemed chest, straight from the shop. Let’s hope there’s something good inside!",
		"The guys at the shop thought you could use these to install some upgrades!",
		"Though these items may be far from festive, they are EPIC and beautiful in their own way nevertheless!",
		"Create levels where things go upside down with these EPIC items!",
		"Epic gift for an epic person, YOU!",
		"Some of the guys at the shop broke their back carrying this package for you, but it was worth it!",
		"Traplight wishes you happy holidays and hopes your new year starts with a big bang, kinda like this chest!",
		"Daily present is ready to open! Twinkle-twinkle!",
		"Get ready to help Santa!",
		"Something pink is shimmering!",
		"Let it snow! ",
		"So huge and heavy gift!",
		"Magnificent antlers - try them on!",
		"Pimp your ride!",
		"Gold is everywhere!",
		"From Skull Rider with love!",
		"Santa might have lost it...",
		"It will keep you warm! ",
		"Something nice for your vehicle! ",
		"I've seen this blue diamond before...",
		"90% off!",
		"Gold fever!",
		"Pink is the new black!",
		"Dangerous beauty!",
		"Make your vehicle EPIC!",
		"Turn the world upside down!",
		"Catch your unicorn!",
		"50% off!",
		"Boost your vehicle to infinity and beyond!",
		"Today is your EPIC day!",
		"What will you do with this fortune?",
		"A very Big Bang!",
		"Best of 2016",
		"Big Bang Racing was chosen among the Best of 2016 by App Store.",
		"We couldn't have done this without you.",
		"Thank you - we love you!",
		"Join our awesome community!",
		"%1 Bundle",
		"Offer ends in",
		"%1 value!",
		"Special Offer",
		"Special Offers",
		"Get more tries",
		"%1 Tries",
		"Out of tries!",
		"Box of Text",
		"Camera Magnet",
		"New Personal Best!",
		"No new record!",
		"Slower than your best: ",
		"New pole position time!",
		"From next reward: ",
		"From pole position: ",
		"Personal best",
		"Final Position",
		"This Tournament is over!",
		"Ends in: ",
		"TOTAL POT",
		"This Tournament is over!",
		"Tournament reward!",
		"Unqualified",
		"Waiting for others to finish",
		"Tournament info",
		"Starts in: %1",
		"TOURNAMENT",
		"Tournament Nitros",
		"Room ",
		" Leaderboard",
		"Time",
		"Prize",
		"Gap",
		"SHARED ACROSS ALL ROOMS",
		" Nitros",
		"FINAL RANKING DEFINES YOUR PRIZE",
		"Winners of each room listed at:",
		"JOIN!",
		"Tournament has ended",
		"Starts in: ",
		"Race!",
		"Claim reward! ",
		"Room results",
		"Join",
		"Improvement: ",
		"Your lead: ",
		"Events",
		"Tournament",
		"One level. Endless restarts. 100 players racing neck-to-neck!",
		"www.BBranks.com",
		"%1`s Tournament",
		"Boosted from ",
		"Capped from ",
		"Golden Helmet",
		"Nickatnyte\u00b4s Hat",
		"Tournament unlocks\nafter level 6",
		"Tournament locked",
		"No active Tournaments",
		" Hours",
		"Ends in: %1",
		"Every participant drives with the same <color=#5fca46>%1</color>, regardless of how much they have upgraded their own vehicles.",
		"Players are divided to rooms of approximately <color=#5fca46>100</color> equally skilled contestants. Match-maker prioritizes placing players into same rooms with their friends.",
		" Unused Nitros will carry over to the next Tournament.",
		"Buying <color=#5fb9ec>Tournament Nitros</color> increases the reward pot of your room!",
		"You can stack and get each pack unlimited times.",
		"At the end of Tournament, the final reward pot along with Treasure Chests are shared among contestants, with fastest players of every room earning the best rewards.",
		" Winner of a room also gets a unique <color=#eccc5f>Golden Helmet</color>!",
		"Enable notifications to be alerted when you lose a Top 10 position",
		"Enable notifications to be alerted when you lose the pole position",
		"<color=#5fb9ec>Tournament Nitros</color> have a fixed performance boost across all players, and are only used inside Tournaments.",
		"Current position",
		"Tournament ends in:",
		"Cam's Red Beanie",
		"PapaJake's Milk Jug",
		"Host:",
		"Room %1 chat",
		"Tap to chat",
		"Track top drivers in realtime: www.BBranks.com",
		"New Messages!",
		"Kitty paw",
		"Previous Season",
		"TOP 3 TEAMS",
		"Teams earn <color=#eccc5f>FREE COINS</color> every week from Racing Seasons!",
		"Season %1",
		"TOP 3 PLAYERS",
		"New racing season has begun! Last season we got %1 Team Trophies and earned %2 coins!",
		"You\u00b4re falling behind! Install upgrades to improve your vehicle!",
		"You need more speed! Get upgrade parts from Chests to improve your vehicle!",
		"Install upgrades, OK!",
		"More treasures, GOT IT!",
		"Time Traveller Hat",
		"Play <color=#f051d9>Good or Bad</color> levels and earn 2x <color=#f051d9>Gem shards</color>!",
		"Continue playing <color=#f051d9>Good or Bad</color> levels normally via floating domes!",
		"This event has ended!",
		"Double Gems!",
		"More to play in: %1",
		"Bandana",
		"Level creators who have earned <color=#71B023>most Likes</color>. Only levels created this month contribute to this leaderboard.",
		"Top Creators",
		"%1 <color=#84F22F>likes to first rank</color>",
		"%1 <color=#84F22F>likes to next rank</color>",
		"Unranked Creator",
		"Fledgling Creator",
		"Aknowledged Creator",
		"Advanced Creator",
		"Veteran Creator",
		"Superstar Creator",
		"Ilmarinen",
		"<color=#84F22F>MAXIMUM RANK</color>",
		"Rank up!",
		"<color=#84F22F>Advanced items</color> are now accessible when building new levels!",
		"Ultimate creator rank reached! You have over 10 million reasons to be proud of yourself!",
		"Awesome!",
		"Cool!",
		"Saved level slots full!",
		"Delete or go live with one SAVED LEVEL to make room for <color=#84F22F>%1</color>.",
		"Edit a LIVE level?",
		"Editing a Live Level makes it unavailable to other players, until you Go Live with it again. 'Likes' and other stats of the level are reset in the process.",
		"To avoid abuse, the cost of editing a Live Level is the amount of coins it has generated you.",
		"Edit",
		"Are you sure you want to delete live level<color=#44c7f0> %1</color>?",
		"Items used in that level will <color=#D20D07>NOT</color> be restored!",
		"Previous Month",
		"Month %1",
		"White Hole",
		"CC platform",
		"Gem Rain",
		"Gem Fountain",
		"Gem Torch",
		"Leaderboard info",
		"100 CC Enforcer",
		"250 CC Enforcer",
		"500 CC Enforcer",
		"800 CC Enforcer",
		"1200 CC Enforcer",
		"Advanced",
		"Warning!",
		"You can only use CC Enforcers in Adventure levels.",
		"You can only use one CC Enforcer in a level. Remove it to use another one.",
		"Earn Likes!",
		"Hunt Trophies!",
		"Create beloved levels to earn Likes! Greatest Adventure levels tend to feature cool surprises and jaw-dropping visuals wrapped into a not-too-challenging driving experience. The best Racing levels on the other hand feature a good continuous flow, have no surprise deaths, and contain multiple spots where to improve your record time and outrun opponents.",
		"Race and outrun your opponents to earn Trophies! By earning enough Trophies, you gain access to higher Leagues which makes new upgrade parts available. Upgrade your vehicle whenever possible to improve its performance and to keep up with the competition! New upgrade parts are found from Treasure Chests, which are earned by playing Racing and Adventure levels, or purchased directly from Shop. Nitros are also found from Treasure Chests, which can greatly boost your racing performance!",
		"Party Hat",
		"Candle Hat",
		"Anniversary",
		"Top 3 Creators",
		"Earn %1 more likes to unlock this category",
		"Report player",
		"If you believe %1 is violating our <color=#97DAFF>Terms of Service</color>, please describe the details below to help us investigate further.",
		"Power Switch",
		"Power Plate",
		"Ice Cream Cone",
		"Land on your wheels!",
		"Me",
		string.Empty
	};
}
